locale: "en"
title: "Site Name"

collections:
  press:
    sort_by: date
    output: true
  donations:
    sort_by: year
    output: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package-lock.json
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - LICENSE.md
  - node_modules
  - src
  - netlify.toml
 
permalink: pretty

future: true
